Add Project Management
Pigmice2733/wiki pull request #19
Opened 2017-10-25 03:51 UTC by ErgoShrimp

Just adding in the start of the project management section (what is in the current PM repo). Includes a basic explanation of the task tracker.

2017-10-25 03:51 UTC, calebeby commented
Deploy preview ready!

Built with commit d5cfdba00d9cfeab443555948929dab84ddb5285

https://deploy-preview-19--pigmice.netlify.com

2017-10-25 03:53 UTC, ErgoShrimp commented
Interesting... the deploy doesn't seem to recognize the changes I made. Any idea what the problem is?

2017-10-25 04:38 UTC, calebeby commented
Works better if you spell `management` right :wink: 

```diff
- [Project Management](project-managment)
+ [Project Management](project-management)
```

2017-10-25 04:43 UTC, ErgoShrimp commented
Thanks, just fixed that. I am also noticing that the markdown syntax isn't translating. Am I missing something obvious or are all of these files somehow not .md files?

2017-10-25 14:33 UTC, calebeby commented
I think you need to put a space after `#`

2017-10-26 04:38 UTC, howardabrams submitted a review, later dismissed

2017-10-26 04:39 UTC, calebeby commented
@ErgoShrimp Is this ready? If so, please add the `ready` label. Thanks!

2017-10-26 14:49 UTC, calebeby requested changes

2017-10-26 14:49 UTC, calebeby commented on project-management/trello.md
> +# Trello
Could we add a screenshot here?

2017-10-26 19:50 UTC, calebeby approved these changes
Thanks!

2017-10-26 19:51 UTC, merged